[tool.poetry]
name = "cipheycore"
version = "0.0.1"
description = ""
authors = ["Cyclic3 <cyclic3.git@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
