name: Linux Release Build
on:
  push: 
    tags:
    - *
jobs:
  build-linux64:
    name: Build Linux64 package
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    strategy:
      fail-fast: false
      matrix:
        abi: ["cp35-cp35m", "cp36-cp36m", "cp37-cp37m", "cp38-cp38"]

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        yum -y install cmake3 boost-devel llvm-toolset-7
    - name: Build Swig
      run: |
        cd /tmp
        curl -L https://github.com/swig/swig/archive/rel-4.0.1.tar.gz -o a.tar.gz
        tar -xzf a.tar.gz
        cd swig*
        ./autogen.sh
        ./configure
        make
        make install
    - name: pip deps
      run: |
       /opt/python/${{matrix.abi}}/bin/python3 -m pip install poetry auditwheel setuptools
    - name: Do build
      run: |
        mkdir build && cd build
        cmake3 .. -DCIPHEY_CORE_TEST=OFF -DCIPHEY_CORE_PYTHON=$(echo /opt/python/${{matrix.abi}}/include/python*) -DCMAKE_BUILD_TYPE=Release
        cmake3 --build .
    - name: Create python package
      run: |
        cd build
        /opt/python/${{matrix.abi}}/bin/python3 -m poetry build
        /opt/python/${{matrix.abi}}/bin/python3 -m auditwheel show dist/*.whl
        /opt/python/${{matrix.abi}}/bin/python3 -m auditwheel repair dist/*.whl
    - name: Upload result
      uses: actions/upload-artifact@v2
      with:
        name: linux64
        path: build
#  build-linux32:
#    name: Build Linux32 package
#    runs-on: ubuntu-latest
#    container: quay.io/pypa/manylinux2014_i686

#    steps:
#    - uses: actions/checkout@v2
#    - name: Install deps
#      run: |
#        yum -y install cmake3 boost-devel ninja-build llvm-toolset-7 python3-pip python3-devel swig3
#        pip3 install poetry auditwheel
##        sudo apt-get install -y cmake clang-4.0 libboost-math-dev ninja-build python3 python3-pip python3-setuptools python3-venv swig
#    - name: Do build
#      run: |
#        mkdir build && cd build
#        cmake3 .. -GNinja -DCIPHEY_CORE_TEST=OFF
#        ninja
#    - name: Create python package
#      run: |
#        cd build
#        poetry build
#        auditwheel show dist/*.whl
#        auditwheel repair dist/*.whl
#    - name: Upload result
#      uses: actions/upload-artifact@v2
#      with:
#        name: linux64
#        path: build/dist

