name: Ciphey Core
on: push
#on:
#  push:
#    branches:
#    - master
#  pull_request:
#    branches:
#    - master
jobs:
  build-linux64:
    name: Build Linux64 package
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt-get install -y cmake g++ libboost-math-dev ninja-build python3 python3-pip python3-setuptools
        pip3 install poetry
    - name: Do build
      run: |
        mkdir build && cd build
        cmake .. -GNinja
        ninja
    - name: Create python package
      run:
        cd build
        poetry build
    - name: Upload result
      uses: actions/upload-artifact@v2
      with:
        name: linux64
        path: build/dist

