name: Release Build
on: push
#on:
#  push:
#    branches:
#    - master
#  pull_request:
#    branches:
#    - master
jobs:
  build-linux64:
    name: Build Linux64 package
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    strategy:
      matrix:
        abi: ["cp35-cp35m", "cp36-cp36m", "cp37-cp37m", "cp38-cp38"]

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        yum -y install cmake3 boost-devel ninja-build llvm-toolset-7 swig3
    - name: overlay hack
      run: |
        cp /opt/python/${{matrix.abi}}/lib/pkgconfig/python*.pc /usr/share/pkgconfig
        cp -rn /opt/python/${{matrix.abi}}/bin/* /usr/bin
    - name: pip deps
      run: |
        pip3 install poetry auditwheel setuptools
    - name: Do build
      run: |
        mkdir build && cd build
        cmake3 .. -GNinja -DCIPHEY_CORE_TEST=OFF -DCIPHEY_PKGCONFIG=ON
        ninja
    - name: Create python package
      run: |
        cd build
        python3 -m poetry build
        python3 -m auditwheel show dist/*.whl
        python3 -m auditwheel repair dist/*.whl
    - name: Upload result
      uses: actions/upload-artifact@v2
      with:
        name: linux64
        path: build
#  build-linux32:
#    name: Build Linux32 package
#    runs-on: ubuntu-latest
#    container: quay.io/pypa/manylinux2014_i686

#    steps:
#    - uses: actions/checkout@v2
#    - name: Install deps
#      run: |
#        yum -y install cmake3 boost-devel ninja-build llvm-toolset-7 python3-pip python3-devel swig3
#        pip3 install poetry auditwheel
##        sudo apt-get install -y cmake clang-4.0 libboost-math-dev ninja-build python3 python3-pip python3-setuptools python3-venv swig
#    - name: Do build
#      run: |
#        mkdir build && cd build
#        cmake3 .. -GNinja -DCIPHEY_CORE_TEST=OFF
#        ninja
#    - name: Create python package
#      run: |
#        cd build
#        poetry build
#        auditwheel show dist/*.whl
#        auditwheel repair dist/*.whl
#    - name: Upload result
#      uses: actions/upload-artifact@v2
#      with:
#        name: linux64
#        path: build/dist

