name: MacOS Release Build
on:
  push: 
    tags: 
    - "*"
jobs:
  build-win64:
    name: Build MacOS package
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        ver: ["@3.7", "@3.8"]

    steps:
    - uses: actions/checkout@v2
    - name: Homebrew deps
      run: |
        brew update
        brew upgrade python${{matrix.ver}} ||  brew install python${{matrix.ver}}
        brew install boost swig
        /usr/local/Cellar/python${{matrix.ver}}/*/Frameworks/Python.framework/Versions/3*/bin/python3 -c "import sys; print(sys.version)"
    - name: Python3 pip deps
      run: |
        /usr/local/Cellar/python${{matrix.ver}}/*/Frameworks/Python.framework/Versions/3*/bin/python3 -m pip install poetry setuptools
    - name: Do build    
      run: |
        mkdir build && cd build
        # Seperate out for variable expansion
        export CIPHEY_PYTHON_INCLUDE=/usr/local/Cellar/python${{matrix.ver}}/*/Frameworks/Python.framework/Versions/3*
        cmake .. -DCIPHEY_CORE_TEST=OFF -DCIPHEY_CORE_PYTHON=$(echo $CIPHEY_PYTHON_INCLUDE) -DCMAKE_BUILD_TYPE=Release
        cmake --build .
    - name: Create python package
      run: |
        cd build
        /usr/local/Cellar/python${{matrix.ver}}/*/Frameworks/Python.framework/Versions/3*/bin/python3 -m poetry build
        mv dist wheelhouse
    - name: Upload result
      uses: actions/upload-artifact@v2
      with:
        name: macos
        path: build
