name: Tests
on: [push]

jobs:
  test:
    name: Test the package
    runs-on: ubuntu-latest
    container: debian
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        apt-get update
        apt-get install -y cmake clang libboost-math-dev ninja-build python3 python3-pip python3-setuptools python3-venv swig  libgtest-dev
        pip3 install poetry auditwheel
    - name: Do build
      run: |
        mkdir build && cd build
        cmake .. -GNinja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
        ninja
    - name: test
      run: |
        cd build
        ctest
