name: Tests
on: [push]

jobs:
  test:
    name: Test the package
    runs-on: ubuntu-latest
    container: debian
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        apt-get update
        apt-get install -y cmake clang libboost-math-dev ninja-build libpython3-dev python3-venv swig libgtest-dev libgmp-dev zlib1g-dev git
    - name: Do build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang
        cmake --build .
    - name: test
      run: |
        cd build
        ctest
