name: Test2
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        mkdir /tmp/foo
        echo hi > /tmp/foo/b
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: foo
        path: /tmp/foo
